include_guard(GLOBAL)

option(BUILD_SHARED_LIBS "Build shared libraries" ON)
option(WAM_BUILD_GWP05 "Compile GWP-0.5 architecture registration" ON)
option(WAM_BUILD_FASTWAM "Compile FastWAM (not available in v0.1)" OFF)
option(WAM_BUILD_SERVER "Install the Python grpcio server/client adapter" OFF)
option(WAM_BUILD_GIGA_WORLD_POLICY
    "Install the open-gigaai/giga-world-policy compatibility adapter" ON)
option(WAM_BUILD_APPS "Build wam-cli and wam-bench" ON)
option(WAM_CUDA "Build the pinned ggml CUDA backend" OFF)
option(WAM_CUDNN "Enable the validated cuDNN path (Phase 6)" OFF)
option(WAM_FP8 "Enable experimental FP8 support (not in v0.1)" OFF)
set(WAM_LLAMA_SOURCE_DIR "" CACHE PATH "Existing llama.cpp b9866 source tree")
set(WAM_LLAMA_ARCHIVE "" CACHE FILEPATH "Offline llama.cpp b9866 source archive")
set(WAM_PROTOC_EXECUTABLE "" CACHE FILEPATH
    "Optional protoc executable used to package wam.desc")

if(NOT WAM_BUILD_GWP05)
    message(FATAL_ERROR "wam.cpp v0.1 requires WAM_BUILD_GWP05=ON")
endif()
if(WAM_BUILD_FASTWAM)
    message(FATAL_ERROR "FastWAM is planned but unsupported in wam.cpp v0.1")
endif()
if(WAM_CUDNN AND NOT WAM_CUDA)
    message(FATAL_ERROR "WAM_CUDNN requires WAM_CUDA=ON")
endif()
if(WAM_FP8)
    message(FATAL_ERROR "FP8 is outside the wam.cpp v0.1 supported scope")
endif()

if(WAM_CUDA)
    enable_language(CUDA)
    find_package(CUDAToolkit REQUIRED)
    set(CMAKE_CUDA_STANDARD 17)
    set(CMAKE_CUDA_STANDARD_REQUIRED ON)
    if(NOT CMAKE_CUDA_ARCHITECTURES)
        message(FATAL_ERROR
            "WAM_CUDA requires explicit CMAKE_CUDA_ARCHITECTURES (80 for A800, 89 for RTX 4090)")
    endif()
endif()
